version: "3.9"

services:
  color1:
    image: robertsilvatech/flask-color
    ports:
      - "5000:5000"
    environment:
      - COLOR=GREEN
    networks:
      - oficina-docker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  oficina-docker:
    external: true