# OF_DOCKER_M08A11 - Trabalhando com volumes no Compose

version: "3.9"

services:
  web-color-2:
    image: robertsilvatech/flask-color
    container_name: color2
    ports:
      - "5001:5000"
    environment:
      - COLOR=BLUE
    networks:
      - frontend-network
    volumes: 
      - app-data:/data
      - app-log:/var/log/

networks:
  frontend-network:
    external: true

volumes:
  app-data: 
  app-log:
    external: true