version: "3.9"

x-template-service: 
  image: robertsilvatech/flask-color
  portas:
    - "5000:5000"
  environment:
    - COLOR=BLUE
  networks:
    - frontend-network

services:
  web-color-1:

networks:
  frontend-network:
    external: true