version: "3.9"

x-template-service: &template-service
  image: robertsilvatech/flask-color
  ports:
    - "5000:5000"
  environment:
    - COLOR=BLUE
  networks:
    - frontend-network

services:
  web-color-1: *template-service

networks:
  frontend-network:
    external: true