# OF_DOCKER_M08A09 - Usando rede externa no Docker Compose

version: "3.9"

services:
  web-color-1:
    image: robertsilvatech/flask-color
    container_name: color1
    ports:
      - "5000:5000"
    environment:
      - COLOR=BLUE
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true