# OF_DOCKER_M08A06 - Criando e executando nosso compose file
# Estrutura padrão

version: "3.9"

services:
  color1:
    container_name: color1
    image: robertsilvatech/flask-color
    ports:
      - "5000:5000"
    environment:
      - COLOR=BLUE
  color2:
    container_name: color2
    image: robertsilvatech/flask-color
    ports:
      - "5005:5000"
    environment:
      - COLOR=RED  
  color3:
    container_name: color3  
    image: robertsilvatech/flask-color
    ports:
      - "5002:5000"
    environment:
      - COLOR=GREEN

# docker container run -p 5000:5000 -e COLOR=CLUE robertsilvatech/flask-color