# OF_DOCKER_M08A06 - Criando e executando nosso compose file
# Estrutura padrão

version: "3.9"

services:
  color1:
    image: robertsilvatech/flask-color
    ports:
      - "5000:5000"
    environment:
      - COLOR=GREEN
    networks:
      - oficina-docker
    deploy:
      replicas: 2

networks:
  oficina-docker:
    external: true