version: "3.9"

services:
  web-color-1:
    image: robertsilvatech/flask-color
    environment:
      - COLOR=BLUE
    networks:
      - compose-lab
    ports:
      - "5000:5000"


networks:
  compose-lab:
    driver: bridge