version: "3.9"

x-template-service: &template-service
    image: robertsilvatech/flask-color
    networks:
      - oficina-docker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      placement:
        constraints:
          - node.labels.ENV==${ENV}      

services:
  color1:
    <<: *template-service
    environment:
      - COLOR=GREEN
  color2:
    <<: *template-service
    environment:
      - COLOR=GREEN
  color3:
    <<: *template-service
    image: robertsilvatech/flaask-color
    environment:
      - COLOR=GREEN
  color4:
    <<: *template-service
    environment:
      - COLOR=GREEN
  color5:
    <<: *template-service
    environment:
      - COLOR=GREEN                        

networks:
  oficina-docker:
    external: true